### ISSUE TITLE
开发者再更新一次吧

### ISSUE THREAD

**Issue by E7KMbb** [cokkeijigen/FuckDMZJ#9]
其实只要去掉自动签到，领取任务奖励之类涉及到帐号的功能就不会导致闪退了

**Comment by cokkeijigen** [comment]
闪退换接口就能解决，可以看看https://github.com/cokkeijigen/FuckDMZJ/pull/7

但是一些广告的关键代码位置每次更新都有可能不一样，就需要每次更新都要去找一遍，实在没那个时间和精力
